### ISSUE TITLE
Question about sign up request

### ISSUE THREAD

**Issue by alvindizon** [alexmamo/FirebaseSignInWithGoogle#1]
First off, great article! I would like to ask--what if I get the same `ApiException: 16: Cannot find a matching credential.` when launching the sign-up request? I followed your guide on my app and when I got that error on sign in request, I launched the sign up request, but still got the same error.

**Comment by AlexMamo** [comment]
Are you sure you're authenticated on the device you're using the app? Be sure to sign in with Google, otherwise, it will not work. Keep me posted.

**Comment by alvindizon** [comment]
Yep, I am authenticated. Your app works on my device BTW, it's just that my own app fails. What other gotchas should I be aware of?

**Comment by AlexMamo** [comment]
What do you mean by "your app"? If you have an issue regarding some code, please add a question on Stackoverflow so I or other developers can take a look at it.

**Comment by alvindizon** [comment]
By my app I mean an app that I created that closely follows the article you made and the code you provided here. In any case I will close this issue, thanks!
