### ISSUE TITLE
Error trying to launch the code on Android Studio

### ISSUE THREAD

**Issue by Mulodji** [alexmamo/FirebaseSignInWithGoogle#2]
Hi Alex!
I was trying to run the code on this repo - without any editing on my part - but I'm getting the following Error.

"Error type 3
Error: Activity class {ro.alexmamo.firebasesigninwithgoogle/ro.alexmamo.firebasesigninwithgoogle.presentation.MainActivity} does not exist"

I don't have any clue about why I'm getting this error. I hope you could shed some light on this issue and point me in the right direction to be able to run your code.
Thanks in advance,
![FirebaseSignInwithGoogle_Error_Type_3_Activity_Class_Does_Not_Exist_2022-08-31 19-26-38](https://user-images.githubusercontent.com/28108633/187759676-220bc89b-cc2b-4a70-802e-1913110fd79b.png)

**Comment by AlexMamo** [comment]
Most likely it has something to do with the Gradle
https://stackoverflow.com/questions/20915266/error-type-3-error-activity-class-does-not-exist
I just run again the project and it worked without an error. Try it also on a real device, and tell me if it works.
