### ISSUE TITLE
signInWithGoogleResponse variable

### ISSUE THREAD

**Issue by IgorIF** [alexmamo/FirebaseSignInWithGoogle#6]
Hi! There should probably be "signInWithGoogleResponse" variable instead of "oneTapSignInResponse".

https://github.com/alexmamo/FirebaseSignInWithGoogle/blob/9e1aedcfc3612526b9316e898cc5fcdb79a2e469/app/src/main/java/ro/alexmamo/firebasesigninwithgoogle/presentation/auth/AuthViewModel.kt#L37

**Comment by AlexMamo** [comment]
Hey Ihor. Yes, you're right. I just updated the AuthViewModel.kt file. Thank you so much.

**Comment by IgorIF** [comment]
Thank you for your work, Alex.

**Comment by AlexMamo** [comment]
You're very welcome, Ihor.
